---
- hosts: all
  tasks:
    - name: Install pip
      apt:
        name: python-pip
        state: present
        update-cache: yes
    - name: Install pexpect
      pip:
        name: pexpect
        state: present
    - name: Install AD Domain packages
      apt: 
        name: 
          - realmd
          - sssd
          - adcli
          - krb5-user
          - sssd-tools
          - samba-common
          - packagekit
          - samba-common-bin
          - samba-libs
        state: present 
        update_cache: yes
    - name: Discover realm
      command: /bin/bash -c "/usr/sbin/realm discover {{ realm_domain }}"
      register: realm_discover_results
      tags: ad

    - name: Discover realm debug
      debug: 
        msg: "{{ realm_discover_results.stdout }}"
    # Check for existing AD
    - name: Checking to see if system is already joined to AD
      command: /bin/bash -c "/usr/sbin/realm list"
      register: realm_list_results
      tags: ad

    - name: Debug realm_list_results
      debug:
        msg: "{{ realm_list_results.stdout }}"

    - name: Join system to AD
      expect:
        command: /bin/bash -c "/usr/sbin/realm join {{ realm_domain }} --user={{ kerberos_user }}"
        responses:
          (?i)Password: "{{ kerberos_user_password }}"  
      ignore_errors: yes
      when: realm_list_results.stdout == ""
      become: true
      tags: ad
