---
	- hosts: all
	  become: true
    vars:
      coredns_version: "1.8.7"
      coredns_install_location: "/opt/coredns"
      coredns_service_user: svc_coredns_user

		tasks: 
      - name: Update Apt Cache
        apt:
          update_cache: yes

      - name: Install Dependencies
        package:
          name: 
            - make

      - name: Download CoreDNS
        get_url:
          url: "https://github.com/coredns/coredns/releases/download/v{{ coredns_version }}/coredns_{{ coredns_version }}_linux_amd64.tgz"
          dest: /tmp/coredns.tgz

      - name: Unarchive CoreDNS
        ansible.builtin.unarchive:
          src: /tmp/coredns.tgz
          dest: "{{ coredns_install_location }}"
          remote_src: yes

      - name: Create CoreDNS User
        ansible.builtin.user:
          name: "{{ coredns_service_user }}"
          comment: "{{ coredns_service_user }} for CoreDNS"
          state: present
          system: yes

      - name: Make CoreDNS log directory
        ansible.builtin.file:
          path: /var/log/CoreDNS
          state: directory
          owner: "{{ coredns_service_user }}"
          group: "{{ coredns_service_user }}"
          mode: '0755'

      - name: Template out service file
        ansible.builtin.template:
          src: coredns.service.j2
          dest:  /etc/systemd/system/coredns
          force: yes

      - name: Template out Corefile
        ansible.builtin.template:
          src: Corefile.j2
          dest: "/etc/coredns/Corefile"
          force: yes



      - name: Shutdown resolve-d service
        ansible.builtin.service:
          name: systemd-resolved
          state: started
          enabled: yes

      - name: Start CoreDNS service
        ansible.builtin.service:
          name: CoreDNS
          state: started
          enabled: yes

      