---
  - hosts: all
    become: true
    vars:
      docker_compose_version: "1.27.4"
    tasks: 

      - name: Fix hardware clock, if required
        shell: 
          cmd: "hwclock --systohc"
          
      - name: Update Apt Cache
        apt:
          update_cache: yes



      - name: Remove old dependencies
        package:
          name: 
            - docker
            - docker-engine
            - docker.io
            - containerd
            - runc
          state: absent

      
      - name: Install dependencies
        package:
          name: 
            - ca-certificates
            - curl
            - gnupg
            - lsb-release
      
      - name: Install docker GPG key
        apt_key:
          url: "https://download.docker.com/linux/ubuntu/gpg"
          state: present
          keyring: "/usr/share/keyrings/docker-archive-keyring.gpg"

      - name: Install APT repo for Docker
        ansible.builtin.apt_repository:
          repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu   bionic stable'
          state: present
          filename: docker.list

      - name: Update Apt Cache
        apt:
          update_cache: yes


      - name: Install Docker
        package:
          name: 
            - docker-ce
            - docker-ce-cli
            - containerd.io
          state: present
      
      - name: Install Docker Compose
        get_url:
          url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
          dest: "/usr/local/bin/docker-compose"
          mode: a+x

      - name: Add command to kill all containers
        lineinfile:
          path: /root/.bash_aliases
          line: "alias docker_killAll='docker container kill $(docker ps -q)'"
          create: yes
      - name: Add command to kill delete all containers
        lineinfile:
          path: /root/.bash_aliases
          line: "alias docker_ctrDeleteAll='docker container rm $(docker ps -a -q)'"
          create: yes
      - name: Add command to kill delete all container images
        lineinfile:
          path: /root/.bash_aliases
          line: "alias docker_imgDeleteAll='docker image rm $(docker images -a -q)'"
          create: yes