---
- hosts: all
  become: true
  vars:
     version: "2022-01-06"
  tasks: 

    

    - name: Download OliveTin
      ansible.builtin.get_url:
        url: "https://github.com/OliveTin/OliveTin/releases/download/{{ version }}/OliveTin_{{ version }}_linux_amd64.deb"
        dest: "/tmp/olivetin.deb"
        force: "yes"

    - name: Install from olivetin.deb
      ansible.builtin.apt:
        deb:  "/tmp/olivetin.deb"

    - name: Deploy OliveTin config file
      ansible.builtin.template:
        src: ./olivetin.yml.j2
        dest: /etc/OliveTin/config.yml
        force: yes
         
    - name: Ensure OliveTin is started
      ansible.builtin.service:
        name: OliveTin
        state: started
        enabled: yes
    