---
  - hosts: all
    become: true
    tasks: 
      - name: Update Apt Cache
        apt:
          update_cache: yes

      - name: Install dependencies
        package:
          name: 
            - make
            - locate

      - name: Make AWX Operator Directory
        ansible.builtin.file:
          path: /opt/awx-operator
          state: directory
          mode: '0755'


      # Git clone
      - name: Download AWX Repo
        ansible.builtin.git:
          repo: 'https://github.com/ansible/awx-operator.git'
          dest: /opt/awx-operator

      # Deploy install script

      - name: Copy a new "awx-prod.yml" file into place, backing up the original if it differs from the copied version
        ansible.builtin.copy:
          src: awx-prod.yml
          dest: /opt/awx-operator
          owner: root
          group: root

      #  

      - name: Install K3
        shell:
          cmd: 'curl -sfL https://get.k3s.io | sh -'
          creates: "/var/lib/rancher/k3s"

      - name: Install Kubernates Dashboard
        shell:
          cmd: 'kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.4.0/aio/deploy/recommended.yaml'


      # kubectl proxy


      - name: Install AWX
        shell:
          cmd: 'kubectl apply -f /opt/awx-operator/awx-prod.yml --namespace=awx-prod'

      